import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f0f0f2",
        "surface-container": "#eeeef0",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ccbdff",
        "on-secondary-fixed-variant": "#564500",
        "inverse-surface": "#2f3132",
        "on-error-container": "#93000a",
        "secondary-container": "#feda5f",
        "tertiary-fixed": "#ffdbcb",
        "on-primary-fixed": "#1f0060",
        "surface-container-highest": "#e2e2e4",
        "surface-dim": "#d9dadc",
        "surface-green-tint": "#d3f5d5",
        tertiary: "#582200",
        "surface-purple-tint": "#e7ddff",
        primary: "#38009d",
        "on-background": "#1a1c1d",
        "on-tertiary-fixed": "#341100",
        "surface-container-low": "#f3f3f5",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#4d26b5",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9fb",
        error: "#ba1a1a",
        "success-green": "#80d882",
        "surface-variant": "#e2e2e4",
        "tertiary-container": "#7c3300",
        secondary: "#725c00",
        "surface-container-high": "#e8e8ea",
        "secondary-fixed-dim": "#e6c44b",
        "on-secondary-fixed": "#231b00",
        "outline-variant": "#cac4d6",
        "primary-container": "#4f29b7",
        "on-tertiary": "#ffffff",
        "info-blue": "#4c96fe",
        "warning-orange": "#f4a664",
        "surface-tint": "#6543cd",
        "primary-fixed": "#e7deff",
        "on-secondary-container": "#755f00",
        surface: "#f9f9fb",
        "on-surface-variant": "#484554",
        "on-tertiary-fixed-variant": "#783100",
        "tertiary-fixed-dim": "#ffb691",
        "on-primary-container": "#bfadff",
        background: "#f9f9fb",
        "error-pink": "#ff8081",
        outline: "#797585",
        "on-tertiary-container": "#ffa170",
        "secondary-fixed": "#ffe07e",
        "error-container": "#ffdad6",
        "inverse-primary": "#ccbdff",
        "on-surface": "#1a1c1d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        "section-gap": "80px",
        "margin-mobile": "16px",
        base: "8px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', "sans-serif"],
        mono: ['"JetBrains Mono"', "Menlo", "monospace"],
        arabic: ['"IBM Plex Sans Arabic"', '"IBM Plex Sans"', "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      animation: {
        "pulse-slow": "pulse 3s ease-in-out infinite",
        shimmer: "shimmer 1.8s infinite",
        "fade-up": "fadeUp 0.3s ease-out both",
        blink: "blink 1s step-end infinite",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
